### PR TITLE
fix(openai): support for 5.x versions

### LINKED ISSUE #642: Support OpenAI SDK v5
Current instrumentation only supports openai SDK from v3.10 to 5.

Version 5 doesn't change the chat completions API paths and can be instrumented without modification

### PR DESCRIPTION
**Pull request by galkleinman**
Resolves #642 

> [!IMPORTANT]
> Updated OpenAI SDK to 5.x, improved error handling, testing, and dependency management in OpenAI instrumentation.
> 
>   - **Behavior**:
>     - Updated OpenAI SDK to version 5.12.2 in `package.json`.
>     - Enhanced manual instrumentation in `OpenAIInstrumentation` to support OpenAI 5.x.
>     - Improved handling of `tool_calls` and `function_calls` in `instrumentation.ts`.
>   - **Error Handling**:
>     - Added comprehensive error handling in `instrumentation.test.ts` for Polly.js.
>     - Improved runtime error handling for `tool_calls` in `instrumentation.ts`.
>   - **Testing**:
>     - Removed HAR network recording fixtures in `instrumentation.test.ts`.
>     - Updated tests to be more resilient with relaxed assertions and guarded setup.
>   - **Dependencies**:
>     - Added `@types/node-fetch` and `node-fetch` as dependencies in `package.json`.
>     - Updated `pnpm-workspace.yaml` with dependency overrides for `form-data` and `tmp`.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=traceloop%2Fopenllmetry-js&utm_source=github&utm_medium=referral)<sup> for 86d5d21a94f724650db6e31f3706c5237dd942f1. You can [customize](https://app.ellipsis.dev/traceloop/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

----

## Summary by CodeRabbit

- New Features
  - Expanded compatibility with newer OpenAI API/SDK versions (v4–v5+).
- Bug Fixes
  - More reliable streaming behavior and tool-call handling.
  - Prevented incorrect span attributes for non-function tool calls.
- Tests
  - Updated and added HAR recordings for chat, streaming, images, and logprobs scenarios.
  - Stabilized tests with improved Polly configuration and extended timeouts for image workflows.
- Chores
  - Dependency updates and workspace overrides to address transitive package versions (form-data, tmp).
  - Updated client/runtime integrations to align with latest OpenAI SDK.

### CODE REVIEW

File: packages/instrumentation-openai/src/instrumentation.ts [hunk 1]
```diff
@@ -486,18 +486,14 @@ export class OpenAIInstrumentation extends InstrumentationBase {
...
             if (toolCall.type) {
-              result.choices[0].message.tool_calls[toolCall.index].type +=
+              result.choices[0].message.tool_calls[toolCall.index].type =
                 toolCall.type;
             }
             if (toolCall.function?.name) {
-              result.choices[0].message.tool_calls[
-                toolCall.index
-              ].function.name += toolCall.function.name;
+              (result.choices[0].message.tool_calls[toolCall.index] as any).function.name += toolCall.function.name;
```
Comment (nirga) [inline packages/instrumentation-openai/src/instrumentation.ts]: weird that it's `+=` no? (I know that it used to be like that)

File: packages/instrumentation-openai/test/instrumentation.test.ts [hunk 2]
```diff
@@ -84,12 +84,14 @@ describe("Test OpenAI instrumentation", async function () {
     contextManager = new AsyncHooksContextManager().enable();
     context.setGlobalContextManager(contextManager);
 
-    const { server } = this.polly as Polly;
-    server.any().on("beforePersist", (_req, recording) => {
-      recording.request.headers = recording.request.headers.filter(
-        ({ name }: { name: string }) => name !== "authorization",
-      );
-    });
+    if (this.polly) {
```
Comment (nirga) [inline packages/instrumentation-openai/test/instrumentation.test.ts:112]: nit: I don't think we need this change

File: packages/instrumentation-openai/test/instrumentation.test.ts [hunk 3]
```diff
@@ -402,14 +404,13 @@ describe("Test OpenAI instrumentation", async function () {
...
       "get_current_weather",
     );
-    assert.deepEqual(
-      JSON.parse(
-        completionSpan.attributes[
-          `${SpanAttributes.LLM_COMPLETIONS}.0.function_call.arguments`
-        ]! as string,
-      ),
-      { location: "Boston" },
+    const functionCallArguments = JSON.parse(
```
Comment (nirga) [inline packages/instrumentation-openai/test/instrumentation.test.ts]: I'd revert it - to make sure it didn't change

File: packages/instrumentation-openai/test/instrumentation.test.ts [hunk 4]
```diff
@@ -502,14 +503,13 @@ describe("Test OpenAI instrumentation", async function () {
       ],
       "get_current_weather",
     );
-    assert.deepEqual(
```
Comment (nirga) [inline packages/instrumentation-openai/test/instrumentation.test.ts:505]: same

File: pnpm-workspace.yaml [hunk 5]
```diff
@@ -1,4 +1,6 @@
 packages:
   - packages/*
+
 overrides:
   form-data@>=4.0.0 <4.0.4: '>=4.0.4'
+  tmp@<=0.2.3: '>=0.2.4'
```
Comment (nirga) [inline pnpm-workspace.yaml:6]: not needed

**Review by nirga — APPROVED** [review]

File: pnpm-workspace.yaml (hunk 5 above)
Comment (galkleinman) [reply pnpm-workspace.yaml:6]: it solves a vulnerability
